'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
type Group={id:number;name:string;memberCount:number;submittedCount:number;status:'open'|'finalized';finalSlots:string[]};
type Mode='home'|'create'|'join'|'schedule'|'result';
const TIMES=['09:00','11:00','14:00','16:00','19:00'];
function nextDays(){return Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i+1);return{key:d.toISOString().slice(0,10),weekday:new Intl.DateTimeFormat('vi-VN',{weekday:'short'}).format(d),day:d.getDate(),month:d.getMonth()+1}})}
export default function Home(){
 const days=useMemo(nextDays,[]),[mode,setMode]=useState<Mode>('home'),[groups,setGroups]=useState<Group[]>([]),[group,setGroup]=useState<Group|null>(null),[groupName,setGroupName]=useState(''),[memberCount,setMemberCount]=useState(4),[personName,setPersonName]=useState(''),[selectedGroupId,setSelectedGroupId]=useState(''),[selected,setSelected]=useState<string[]>([]),[loading,setLoading]=useState(false),[notice,setNotice]=useState('');
 const loadGroups=async()=>{const r=await fetch('/api/groups',{cache:'no-store'});if(r.ok)setGroups(await r.json())};useEffect(()=>{loadGroups()},[]);
 const createGroup=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setNotice('');const r=await fetch('/api/groups',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:groupName,memberCount})});const d=await r.json();setLoading(false);if(!r.ok)return setNotice(d.error||'Chưa thể tạo nhóm.');setGroup(d);setMode('schedule')};
 const joinGroup=(e:FormEvent)=>{e.preventDefault();const found=groups.find(g=>String(g.id)===selectedGroupId);if(!found)return setNotice('Hãy chọn một nhóm nhé.');setGroup(found);setMode(found.status==='finalized'?'result':'schedule')};
 const toggleSlot=(slot:string)=>setSelected(v=>v.includes(slot)?v.filter(s=>s!==slot):[...v,slot]);
 const submitAvailability=async()=>{if(!group||!personName.trim()||!selected.length)return setNotice('Nhập tên và chọn ít nhất một khung giờ nhé.');setLoading(true);setNotice('');const r=await fetch(`/api/groups/${group.id}/availability`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({personName,slots:selected})});const d=await r.json();setLoading(false);if(!r.ok)return setNotice(d.error||'Chưa thể lưu lịch.');setGroup(d);await loadGroups();setMode('result')};
 const reset=()=>{setMode('home');setGroup(null);setPersonName('');setSelected([]);setNotice('');loadGroups()};
 return <main><nav className="nav"><button className="brand" onClick={reset}><span>♡</span> Hẹn nha!</button><div className="nav-note"><i/>Rảnh lúc nào, chốt lúc đó</div></nav><section className="shell"><header className="page-heading"><h1>Chốt lịch lẹ lên!!!</h1><p><span>1</span> Tạo nhóm <b>→</b><span>2</span> Chọn lịch rảnh <b>→</b><span>3</span> Chờ đủ người <b>→</b><span>4</span> Chốt kèo ✨</p></header><div className="card">
 {mode==='home'&&<><div className="card-head"><span className="icon lavender">☻</span><div><p>BẮT ĐẦU THÔI</p><h2>M là người...</h2></div></div><button className="choice peach" onClick={()=>setMode('create')}><span className="choice-icon">＋</span><div><b>Tạo nhóm mới</b><small>Đặt tên nhóm và số thành viên</small></div><strong>›</strong></button><div className="or"><span/>hoặc<span/></div><button className="choice mint" onClick={()=>{setMode('join');loadGroups()}}><span className="choice-icon">⌁</span><div><b>Tham gia nhóm</b><small>Chọn nhóm đã có trong danh sách</small></div><strong>›</strong></button><p className="privacy">♧ Không cần tài khoản · Ai cũng vào được</p></>}
 {mode==='create'&&<form onSubmit={createGroup}><Back onClick={()=>setMode('home')}/><div className="card-head"><span className="icon peach-bg">＋</span><div><p>TẠO CUỘC HẸN</p><h2>Nhóm m tên gì?</h2></div></div><label>Tên nhóm<input autoFocus required maxLength={40} placeholder="Ví dụ: Team đi Đà Lạt" value={groupName} onChange={e=>setGroupName(e.target.value)}/></label><label>Số thành viên<div className="counter"><button type="button" onClick={()=>setMemberCount(Math.max(2,memberCount-1))}>−</button><b>{memberCount}</b><button type="button" onClick={()=>setMemberCount(Math.min(20,memberCount+1))}>＋</button></div></label><label>Tên của m<input required maxLength={30} placeholder="M tên gì?" value={personName} onChange={e=>setPersonName(e.target.value)}/></label>{notice&&<p className="notice">{notice}</p>}<button className="primary" disabled={loading}>{loading?'Đang tạo...':'Tạo nhóm & chọn lịch →'}</button></form>}
 {mode==='join'&&<form onSubmit={joinGroup}><Back onClick={()=>setMode('home')}/><div className="card-head"><span className="icon mint-bg">⌁</span><div><p>THAM GIA CUỘC HẸN</p><h2>Chọn nhóm của m</h2></div></div><label>Nhóm đang mở<select required value={selectedGroupId} onChange={e=>setSelectedGroupId(e.target.value)}><option value="">— Chọn một nhóm —</option>{groups.filter(g=>g.status==='open').map(g=><option key={g.id} value={g.id}>{g.name} · {g.submittedCount}/{g.memberCount} người</option>)}</select></label>{!groups.some(g=>g.status==='open')&&<p className="empty">Chưa có nhóm nào đang mở. M tạo nhóm mới đi!</p>}<label>Tên của m<input required maxLength={30} placeholder="M tên gì?" value={personName} onChange={e=>setPersonName(e.target.value)}/></label>{notice&&<p className="notice">{notice}</p>}<button className="primary">Tiếp tục chọn lịch →</button></form>}
 {mode==='schedule'&&group&&<><Back onClick={reset}/><div className="schedule-title"><div><p>NHÓM</p><h2>{group.name}</h2></div><span>{group.submittedCount}/{group.memberCount} người đã chọn</span></div><p className="hint">Ê <b>{personName}</b>! Chạm hết mấy khung giờ m rảnh đi.</p><div className="calendar"><div className="time-label">Giờ</div>{days.map(d=><div className="day" key={d.key}><small>{d.weekday}</small><b>{d.day}</b><small>thg {d.month}</small></div>)}{TIMES.flatMap(time=>[<div className="time" key={time}>{time}</div>,...days.map(d=>{const slot=`${d.key}T${time}`;return <button type="button" aria-label={`${d.key} ${time}`} key={slot} onClick={()=>toggleSlot(slot)} className={selected.includes(slot)?'slot selected':'slot'}>{selected.includes(slot)?'✓':''}</button>})])}</div>{notice&&<p className="notice">{notice}</p>}<div className="submit-row"><span>Đã chọn <b>{selected.length}</b> khung giờ</span><button className="primary compact" disabled={loading} onClick={submitAvailability}>{loading?'Đang lưu...':'Xong, lưu lịch →'}</button></div></>}
 {mode==='result'&&group&&<><Back onClick={reset}/><div className="result-icon">{group.status==='finalized'?'🎉':'✓'}</div><p className="result-kicker">{group.status==='finalized'?'CHỐT KÈO THÀNH CÔNG':'ĐÃ LƯU LỊCH CỦA M'}</p><h2 className="result-title">{group.name}</h2>{group.status==='finalized'?<><p className="result-copy">Tất cả đã trả lời! Khung giờ hợp nhau nhất là:</p><div className="final-slots">{group.finalSlots.length?group.finalSlots.map(s=><div key={s}><b>{new Date(s).toLocaleDateString('vi-VN',{weekday:'long',day:'numeric',month:'long'})}</b><span>{s.slice(11,16)}</span></div>):<p>Chưa có khung giờ nào tất cả cùng rảnh. Cả nhóm thử trao đổi thêm nhé.</p>}</div></>:<><p className="result-copy">Còn <b>{group.memberCount-group.submittedCount} người</b> nữa. Khi đủ thành viên, lịch chung sẽ tự động được chốt.</p><div className="progress"><i style={{width:`${group.submittedCount/group.memberCount*100}%`}}/></div><small className="waiting">{group.submittedCount}/{group.memberCount} người đã hoàn thành</small></>}<button className="secondary" onClick={reset}>Về trang chính</button></>}
 </div></section><footer>Made for những cuộc hẹn không bị “để tính sau” ♡</footer></main>
}
function Back({onClick}:{onClick:()=>void}){return <button type="button" className="back" onClick={onClick}>← Quay lại</button>}
